version: 1.10.0
history:
  1.10.0:
    date: '2024-02-19'
    title: Crypt
    description: 'Add Crypt in Tools menu.'
  1.9.0:
    date: '2023-12-13'
    title: Icons, Tools
    description: 'Add icons to menu. Open tools in modals.'
  1.8.0:
    date: '2023-12-13'
    title: Spec
    description: 'Add spec support.'
  1.7.0:
    date: '2023-03-27'
    title: Bootstrap
    description: 'Using version 5.'
  1.6.0:
    date: '2023-03-21'
    title: 'Password'
    description: 'Add password generator.'
  1.5.0:
    date: '2022-10-13'
    title: 'Plugin db/sync_v1'
    description: 'Change admin layout to Bootstrap 4.'
  1.4.3:
    date: '2022-09-28'
    title: 'Layout'
    description: 'Minor layout changes on page /buto_sys_mercury.'
  1.4.2:
    date: '2022-09-28'
    title: 'Online'
    description: 'Add online indicator plugin.'
  1.4.1:
    date: '2022-09-07'
    title: 'Language'
    description: 'Change language from sv to en.'
  1.4.0:
    date: '2021-11-15'
    title: 'wf/account2, lab/sync'
    description: 'Add remember params and signin event to wf/account2. Adjustments due to lab/sync.'
  1.3.1:
    date: '2021-11-15'
    title: 'Mercury'
    description: 'Add border on pre tags for better visibility.'
  1.3.0:
    date: '2021-11-02'
    title: 'Sync'
    description: 'Add remote param.'
  1.2.0:
    date: '2021-04-06'
    title: 'Bootstrap'
    description: 'Add Bootstrap 4 support for Home and MySql.'
  1.1.4:
    date: '2020-11-06'
    title: 'Dump'
    description: 'Stop dumping data.'
  1.1.3:
    date: '2020-10-29'
    title: 'Bootstrap 4'
    description: 'Add Bootstrap 4 support for PluginPluginAnalysis.'
  1.1.2:
    date: '2020-10-29'
    title: 'Bootstrap 4'
    description: 'Add Bootstrap 4 support for PluginMailQueue_admin and PluginAccountAdmin_v1.'
  1.1.1:
    date: '2020-10-28'
    title: 'Bootstrap 4'
    description: 'Add Bootstrap 4 support starting with PluginLabSync.'
  1.1.0:
    date: '2020-08-25'
    title: Unique rows
    description: 'Add page to render unique rows.'
  1.0.3:
    date: '2020-06-01'
    title: Wider layout
    description: Using class container-fluid in main.yml file.
  1.0.2:
    date: '2020-03-26'
    title: Pull repos existing environment
    description: Add file git/pull_theme_dev_theme.sh to pull this theme into existing environment.
  1.0.1:
    date: '2020-03-16'
    title: Pull repos
    description: Add file git/pull.sh to pull all repos.
