dump: false
default_class: d
default_method: home
i18n:
  language: en
  languages:
    - en
plugin_modules:
  mailqueueadmin:
    plugin: 'mail/queue_admin'
    settings:
      admin_layout: /theme/[theme]/layout/main_bs4.yml
  d:
    plugin: 'wf/doc'
  account:
    plugin: 'wf/account2'
    settings:
      allow:
        signin: true
        signin_method: username
        registration: false
        change_email: false
        change_password: false
        two_factor_authentication: false
        remember: true
        remember_signout_username: true
      two_factor_authentication:
        key_timeout: 600
      mysql: 'yml:/../buto_data/theme/[theme]/mysql.yml'
      phpmailer: 'yml:/../buto_data/theme/[theme]/plugin_wf_account2_phpmailer.yml'
      sms_pixie:
        account: _
        pwd: _
        sender: '_'
      on_signin:
        script: "location.href='/';"
      on_activate:
        script: "location.href='/';"
  users:
    plugin: 'account/admin_v1'
    settings:
      admin_layout: /theme/[theme]/layout/main_bs4.yml
  plugin_analysis:
    plugin: 'plugin/analysis'
    settings:
      admin_layout: /theme/[theme]/layout/main_bs4.yml
  sync:
    plugin: 'lab/sync'
    settings:
      admin_layout: /theme/[theme]/layout/main_bs4.yml
  i18n:
    plugin: 'i18n/json_v1'
  dbsync:
    plugin: 'db/sync_v1'
    settings:
      admin_layout: /theme/[theme]/layout/main_bs4.yml
      item: 'yml:/../buto_data/theme/[theme]/plugin_db_sync_v1_item.yml'
  html_to_yml:
    plugin: 'buto/html_to_yml'
  json_to_yml:
    plugin: 'buto/json_to_yml'
  unique_rows:
    plugin: 'buto/unique_rows'
  str_replace:
    plugin: 'buto/str_replace'
  editor:
    plugin: 'wf/editor'
    settings:
      admin_layout: /theme/[theme]/layout/main.yml
  password:
    plugin: 'password/generator'
    settings:
      admin_layout: /theme/[theme]/layout/main_bs4.yml
plugin:
  theme:
    include:
      enabled: true
  readme:
    yml:
      enabled: true
  navigator:
    online:
      enabled: true
events:
  shutdown:
    -
      plugin: 'wf/errorhandling'
      method: 'shutdown'
      data:
        alert: true
        log: false
        email: false
        slack: false
        slack_settings:
          webhook: _
          group: _
  document_render_string:
    -
      plugin: i18n/translate_v1
      method: translate_string
  sys_close:
    -
      plugin: 'wf/dump'
      method: dump
  load_theme_config_settings_after:
    -
      plugin: 'wf/account2'
      method: signin
